use std::path::{Path, PathBuf};
use std::process::Command;

use crate::error::IsolaError;
use crate::paths;
use crate::sandbox::rootfs;

fn lima_vm_name(name: &str) -> String {
    format!("isola-{name}")
}

fn is_lima_installed() -> bool {
    Command::new("limactl")
        .arg("--version")
        .stdout(std::process::Stdio::null())
        .stderr(std::process::Stdio::null())
        .status()
        .map(|s| s.success())
        .unwrap_or(false)
}

fn vm_exists(name: &str) -> bool {
    let vm = lima_vm_name(name);
    Command::new("limactl")
        .args(["list", "--json"])
        .output()
        .ok()
        .map(|o| {
            if !o.status.success() {
                return false;
            }
            let text = String::from_utf8_lossy(&o.stdout);
            text.lines().any(|line| {
                serde_json::from_str::<serde_json::Value>(line)
                    .ok()
                    .and_then(|v| v["name"].as_str().map(|n| n == vm))
                    .unwrap_or(false)
            })
        })
        .unwrap_or(false)
}

fn is_vm_running(name: &str) -> bool {
    let vm = lima_vm_name(name);
    Command::new("limactl")
        .args(["list", "--json"])
        .output()
        .ok()
        .and_then(|o| {
            if !o.status.success() {
                return None;
            }
            let text = String::from_utf8_lossy(&o.stdout);
            for line in text.lines() {
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(line) {
                    if v["name"].as_str() == Some(&vm) {
                        return Some(v["status"].as_str() == Some("Running"));
                    }
                }
            }
            None
        })
        .unwrap_or(false)
}

fn ensure_vm_running(name: &str) -> Result<(), IsolaError> {
    let vm = lima_vm_name(name);
    if is_vm_running(name) {
        return Ok(());
    }
    eprintln!("Starting VM '{vm}'...");
    let status = Command::new("limactl")
        .args(["start", &vm])
        .status()
        .map_err(|e| IsolaError::ConfigError(format!("Failed to start Lima VM: {e}")))?;
    if !status.success() {
        return Err(IsolaError::ConfigError(format!(
            "Failed to start Lima VM '{vm}'. Run `limactl start {vm}` manually to debug."
        )));
    }
    Ok(())
}

fn generate_lima_yaml(workspace: Option<&Path>) -> String {
    let mut yaml = String::from(
        r#"# Generated by isola
images:
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-amd64.img"
    arch: "x86_64"
  - location: "https://cloud-images.ubuntu.com/releases/24.04/release/ubuntu-24.04-server-cloudimg-arm64.img"
    arch: "aarch64"
cpus: 4
memory: "4GiB"
disk: "20GiB"
mountType: "virtiofs"
"#,
    );

    if let Some(ws) = workspace {
        yaml.push_str(&format!(
            r#"mounts:
  - location: "{}"
    mountPoint: "/workspace"
    writable: true
"#,
            ws.display()
        ));
    }

    yaml
}

fn build_post_setup_script(name: &str, environments: &[String]) -> String {
    let claude_md = rootfs::build_claude_md(environments);
    let settings_json = serde_json::json!({
        "permissions": {
            "defaultMode": "bypassPermissions",
            "allow": [
                "Bash", "Read", "Edit", "Write", "Glob", "Grep",
                "WebFetch", "WebSearch", "Agent", "NotebookEdit"
            ],
            "deny": []
        }
    });
    let settings_str = serde_json::to_string_pretty(&settings_json).unwrap();

    let gitconfig = rootfs::build_host_gitconfig().unwrap_or_default();

    let mut script = String::from("#!/bin/bash\nset -e\n\n");

    // Hostname and hosts
    script.push_str(&format!("echo '{}' > /etc/hostname\n", name));
    script.push_str(&format!(
        "printf '127.0.0.1 localhost {}\\n::1 localhost {}\\n' > /etc/hosts\n",
        name, name
    ));

    // APT sandbox config
    script.push_str("mkdir -p /etc/apt/apt.conf.d\n");
    script.push_str("echo 'APT::Sandbox::User \"root\";' > /etc/apt/apt.conf.d/99sandbox\n\n");

    // Directories
    for dir in &[
        "/workspace",
        "/root/.claude",
        "/home/sandbox/.claude",
        "/usr/local/bin",
    ] {
        script.push_str(&format!("mkdir -p {dir}\n"));
    }

    // Empty credentials file
    script.push_str("touch /home/sandbox/.claude/.credentials.json\n\n");

    // Settings JSON (use base64 to avoid heredoc delimiter issues)
    script.push_str(&format!(
        "cat > /home/sandbox/.claude/settings.json << 'ISOLA_SETTINGS_EOF'\n{settings_str}\nISOLA_SETTINGS_EOF\n"
    ));
    script.push_str(&format!(
        "cat > /root/.claude/settings.json << 'ISOLA_SETTINGS_EOF'\n{settings_str}\nISOLA_SETTINGS_EOF\n\n"
    ));

    // CLAUDE.md
    script.push_str(&format!(
        "cat > /home/sandbox/.claude/CLAUDE.md << 'ISOLA_CLAUDE_EOF'\n{claude_md}\nISOLA_CLAUDE_EOF\n"
    ));
    script.push_str(&format!(
        "cat > /workspace/CLAUDE.md << 'ISOLA_CLAUDE_EOF'\n{claude_md}\nISOLA_CLAUDE_EOF\n\n"
    ));

    // Git config
    if !gitconfig.is_empty() {
        script.push_str(&format!(
            "cat > /home/sandbox/.gitconfig << 'ISOLA_GIT_EOF'\n{gitconfig}\nISOLA_GIT_EOF\n"
        ));
        script.push_str(&format!(
            "cat > /root/.gitconfig << 'ISOLA_GIT_EOF'\n{gitconfig}\nISOLA_GIT_EOF\n\n"
        ));
    }

    // Install Claude Code (ensure Node.js is available)
    script.push_str(
        r#"echo ">>> Installing Claude Code..."
if ! command -v node &> /dev/null; then
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash -
    apt-get install -y nodejs || true
    dpkg --configure -a --force-overwrite 2>/dev/null || true
fi
npm install -g @anthropic-ai/claude-code || true
echo ">>> Post-setup complete"
"#,
    );

    script
}

/// Shell-escape a value by wrapping in single quotes.
fn shell_escape(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

// --- Public API ---

pub fn preflight_checks() -> Result<(), IsolaError> {
    if !is_lima_installed() {
        return Err(IsolaError::ConfigError(
            "Lima is not installed. Install with: brew install lima\n\
             See https://lima-vm.io/ for details."
                .into(),
        ));
    }
    Ok(())
}

pub fn create_sandbox(
    name: &str,
    workspace: Option<&Path>,
    environments: &[String],
) -> Result<(), IsolaError> {
    let sandbox_dir = paths::sandbox_dir(name);
    std::fs::create_dir_all(&sandbox_dir)?;

    let yaml = generate_lima_yaml(workspace);
    let yaml_path = sandbox_dir.join("lima.yaml");
    std::fs::write(&yaml_path, &yaml)?;

    let vm = lima_vm_name(name);

    eprintln!("Creating Lima VM '{vm}'...");
    let status = Command::new("limactl")
        .args(["create", "--name", &vm, &yaml_path.to_string_lossy()])
        .status()
        .map_err(|e| IsolaError::ConfigError(format!("Failed to create Lima VM: {e}")))?;
    if !status.success() {
        return Err(IsolaError::ConfigError(format!(
            "Failed to create Lima VM '{vm}'"
        )));
    }

    eprintln!("Starting VM '{vm}'...");
    let status = Command::new("limactl")
        .args(["start", &vm])
        .status()
        .map_err(|e| IsolaError::ConfigError(format!("Failed to start Lima VM: {e}")))?;
    if !status.success() {
        return Err(IsolaError::ConfigError(format!(
            "Failed to start Lima VM '{vm}'"
        )));
    }

    // Run post-setup inside VM
    let post_setup = build_post_setup_script(name, environments);
    let exit_code = run_command(name, &post_setup)?;
    if exit_code != 0 {
        eprintln!("Warning: post-setup script exited with code {exit_code}");
    }

    Ok(())
}

pub fn enter_sandbox(
    name: &str,
    shell: bool,
    _workspace: Option<PathBuf>,
) -> Result<i32, IsolaError> {
    if !vm_exists(name) {
        return Err(IsolaError::SandboxNotFound(name.to_string()));
    }
    ensure_vm_running(name)?;

    let vm = lima_vm_name(name);

    if shell {
        // Root shell
        let status = Command::new("limactl")
            .args(["shell", &vm, "--", "sudo", "bash"])
            .status()
            .map_err(|e| IsolaError::ConfigError(format!("Failed to enter VM: {e}")))?;
        Ok(status.code().unwrap_or(1))
    } else {
        // Claude Code as sandbox user
        let mut cmd = String::from("cd /workspace 2>/dev/null\n");

        // Forward key environment variables
        for var in &[
            "ANTHROPIC_API_KEY",
            "TERM",
            "COLORTERM",
            "FORCE_COLOR",
            "NO_COLOR",
            "CLICOLOR_FORCE",
            "CLAUDE_CODE_USE_BEDROCK",
            "CLAUDE_CODE_USE_VERTEX",
            "AWS_REGION",
            "AWS_ACCESS_KEY_ID",
            "AWS_SECRET_ACCESS_KEY",
            "AWS_SESSION_TOKEN",
        ] {
            if let Ok(val) = std::env::var(var) {
                cmd.push_str(&format!("export {}={}\n", var, shell_escape(&val)));
            }
        }

        cmd.push_str(
            "exec sudo -u sandbox -E \
             env PATH=/home/sandbox/.cargo/bin:/home/sandbox/.local/bin:/usr/local/bin:/usr/bin:/bin \
             HOME=/home/sandbox \
             LANG=C.UTF-8 \
             /usr/local/bin/claude --dangerously-skip-permissions",
        );

        let status = Command::new("limactl")
            .args(["shell", &vm, "--", "sudo", "bash", "-c", &cmd])
            .status()
            .map_err(|e| IsolaError::ConfigError(format!("Failed to enter VM: {e}")))?;
        Ok(status.code().unwrap_or(1))
    }
}

pub fn exec_command(
    name: &str,
    command: Vec<String>,
    _workspace: Option<PathBuf>,
) -> Result<i32, IsolaError> {
    if command.is_empty() {
        return Err(IsolaError::ConfigError("no command specified".to_string()));
    }
    if !vm_exists(name) {
        return Err(IsolaError::SandboxNotFound(name.to_string()));
    }
    ensure_vm_running(name)?;

    let vm = lima_vm_name(name);

    // Build command string with proper escaping
    let mut cmd = String::from("cd /workspace 2>/dev/null\n");

    // Forward key env vars
    for var in &["ANTHROPIC_API_KEY", "TERM"] {
        if let Ok(val) = std::env::var(var) {
            cmd.push_str(&format!("export {}={}\n", var, shell_escape(&val)));
        }
    }

    let escaped_args: Vec<String> = command.iter().map(|arg| shell_escape(arg)).collect();
    cmd.push_str(&format!(
        "exec sudo -u sandbox -E \
         env PATH=/home/sandbox/.cargo/bin:/home/sandbox/.local/bin:/usr/local/bin:/usr/bin:/bin \
         HOME=/home/sandbox \
         LANG=C.UTF-8 \
         {}",
        escaped_args.join(" ")
    ));

    let status = Command::new("limactl")
        .args(["shell", &vm, "--", "sudo", "bash", "-c", &cmd])
        .status()
        .map_err(|e| IsolaError::ConfigError(format!("Failed to exec in VM: {e}")))?;
    Ok(status.code().unwrap_or(1))
}

pub fn run_command(name: &str, command: &str) -> Result<i32, IsolaError> {
    let vm = lima_vm_name(name);
    let status = Command::new("limactl")
        .args(["shell", &vm, "--", "sudo", "bash", "-c", command])
        .status()
        .map_err(|e| IsolaError::ConfigError(format!("Failed to run command in VM: {e}")))?;
    Ok(status.code().unwrap_or(1))
}

pub fn destroy_sandbox(name: &str) -> Result<(), IsolaError> {
    let vm = lima_vm_name(name);

    // Stop and delete Lima VM
    if vm_exists(name) {
        eprintln!("Deleting Lima VM '{vm}'...");
        let status = Command::new("limactl")
            .args(["delete", "--force", &vm])
            .status()
            .map_err(|e| IsolaError::ConfigError(format!("Failed to delete Lima VM: {e}")))?;
        if !status.success() {
            eprintln!("Warning: Lima VM deletion may have failed");
        }
    }

    // Remove isola config directory
    let sandbox_dir = paths::sandbox_dir(name);
    if sandbox_dir.exists() {
        std::fs::remove_dir_all(&sandbox_dir)?;
    }

    eprintln!("Sandbox '{}' destroyed", name);
    Ok(())
}

pub fn setup_host() -> Result<(), IsolaError> {
    eprintln!("No host setup required on macOS.");
    eprintln!("Ensure Lima is installed: brew install lima");
    if is_lima_installed() {
        eprintln!("Lima is installed and ready.");
    } else {
        eprintln!("Lima is NOT installed. Run: brew install lima");
    }
    Ok(())
}

pub fn reprovision(name: &str, environments: &[String]) -> Result<(), IsolaError> {
    if !vm_exists(name) {
        return Err(IsolaError::SandboxNotFound(name.to_string()));
    }
    ensure_vm_running(name)?;

    // Run post-setup
    let post_setup = build_post_setup_script(name, environments);
    let exit_code = run_command(name, &post_setup)?;
    if exit_code != 0 {
        eprintln!("Warning: post-setup script exited with code {exit_code}");
    }

    // Run provisioning
    let script = rootfs::build_provision_script(environments);
    eprintln!("Re-provisioning '{}': {}...", name, environments.join(", "));
    let exit_code = run_command(name, &script)?;
    if exit_code != 0 {
        return Err(IsolaError::ProvisionFailed(exit_code));
    }

    eprintln!("Sandbox '{}' re-provisioned successfully!", name);
    Ok(())
}
